### ISSUE TITLE
feat: Allow to add mentions in question and answer

### ISSUE THREAD

**Issue by kedaroh-bh** [drodil/backstage-plugin-qeta#162]
**Feature:**
Allow to add mentions (users or groups) in question and answer.

**Description:**
While asking a question or answering any question user can mention any other user by typing character '@' which will open a list of users and as on typing the list will be filter accordingly, once user select an item from list and submit the question/answer that mentioned user/group will be saved in DB.

**Future Scope:**
Send a notification to mentioned user/group of user.

**Comment by drodil** [comment]
Hi, thanks for this feature proposal. It's been on my mind since starting to work with the plugin but unfortunately haven't found time to implement it. The biggest problem is probably the UI side as it's not very easy to make it right to detect the start of mentioning,  and when to close the mention pop-up list. 

I'm not sure if it requires a new table for the users/groups mentioned though; those probably could be detected on runtime from the question/answer content and send notification/highlight based on that. The mentions should probably also link to the user/group page in catalog when the content is rendered.

**Comment by drodil** [comment]
Ah, there was already an issue open for this #86

**Comment by kedaroh-bh** [comment]
My bad, closing this, we will continue discussion there.
