### ISSUE TITLE
feat: Show truncated content for question in questions list

### ISSUE THREAD

**Issue by Revyy** [drodil/backstage-plugin-qeta#50]
Showing a truncated version of the question content in the questions list might be cool and helpful? 

What do you think?

If you like it I would be willing to try and implement it.

![Screenshot 2023-03-16 at 09 27 31](https://user-images.githubusercontent.com/9215529/225558679-a3f9a015-4314-48d9-be56-db13c0789fe1.png)

**Comment by drodil** [comment]
Nice, it can give some more context in the list, I like it. As long as it stays in one line. Only problem might be that if your question starts for example with Markdown codeblock.. The rendering of that might look a bit silly if it's just rendered as plain text. You might want to figure out if the MarkdownContent component could be made so that it only renders the first line of the question?

**Comment by Revyy** [comment]
Yeah good point! I'll try some things out to try and cover those kinds of corner cases.

**Comment by drodil** [comment]
This is done and shipped, thanks for the contribution @Revyy !
