### ISSUE TITLE
feat: Moderator access

### ISSUE THREAD

**Issue by anestor6** [drodil/backstage-plugin-qeta#81]
Anyway we can add moderator access? I think a quick solution would be to allow to paste in a userid's in the config under a stanza like "moderator" so something like 
```
qeta
    moderators: ['user:/anestor6', ...]
    ...
```

moderator access would allow these user to delete and edit existing questions. Thoughts?

**Comment by drodil** [comment]
This relates highly to #75 

App config is one way to do this but I am not sure if this should be done with Backstage permission framework instead.  Changing the current BasicPermissions to be ResourcePermissions instead could be maybe utilized. Of course, this would be a breaking change as the checks for permissions would need to be configured for applications that do not have those yet or everyone would be allowed to edit any question/answer. 

Having the moderators in the app config is another way to go, but requires always a config change to add or remove people which is a bit more cumbersome especially if you have the RBAC plugin available in Backstage. But we can go with that for now since the permission framework is restricted in means of what can be passed to the permission evaluator (only string).  

Adding the moderators config is quite straight forward but keep in mind that this also requires changes to the SQL queries as the checks for owning the question/answer are all the way down there. 

Are you willing to contribute a PR for this?
